server:
  port: 5100
  
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true
  
spring:
 
#  profiles:
#    active: test
#  datasource:
#    url: jdbc:mysql://localhost:3306/micro_services
#    username: ${MYSQL_USER:root}
#    password: ${MYSQL_PASSWORD:}

  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

#   datasource:
#    url: jdbc:h2:mem:productdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  

    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        
  application:
    name: product-service